#!/usr/bin/env bash
#
# Point the external APISIX gateway at the internal billing gateway.
#
# APISIX here runs in "traditional" role with etcd as its config provider
# (see api/ansible/roles/apisix), so routes are not Kubernetes objects - they
# are written through the Admin API, which is ClusterIP-only on port 9180.
# Run `make port-forward` in another shell first, or point APISIX_ADMIN_URL
# somewhere reachable.
#
# Usage:
#   APISIX_ADMIN_KEY=<key> ./seed-routes.sh            # create / update
#   APISIX_ADMIN_KEY=<key> ./seed-routes.sh --delete   # remove everything
#
# The admin key is generated by the ansible run and stored on the controller
# at api/ansible/.secrets/apisix_admin_key.
#
# Environment:
#   APISIX_ADMIN_URL    default http://127.0.0.1:9180
#   APISIX_ADMIN_KEY    required
#   UPSTREAM_NODE       default billing-getway-internal.default.svc.cluster.local:8081
#                       (override for another namespace, or to point a second
#                       APISIX at this gateway)
#   ADMIN_ALLOW_CIDRS   optional, comma-separated. When set, the admin route
#                       below is wrapped in ip-restriction and only these
#                       CIDRs can call the admin endpoints.
set -euo pipefail

ADMIN_URL="${APISIX_ADMIN_URL:-http://127.0.0.1:9180}"
ADMIN_KEY="${APISIX_ADMIN_KEY:-}"
UPSTREAM_NODE="${UPSTREAM_NODE:-billing-getway-internal.default.svc.cluster.local:8081}"
ADMIN_ALLOW_CIDRS="${ADMIN_ALLOW_CIDRS:-}"

UPSTREAM_ID="billing-getway-internal"
ROUTE_MOBILE_ID="billing-getway-mobile"
ROUTE_ADMIN_ID="billing-getway-admin"

if [ -z "$ADMIN_KEY" ]; then
  echo "APISIX_ADMIN_KEY is required (see api/ansible/.secrets/apisix_admin_key)" >&2
  exit 1
fi

# call <method> <path> [body]
# Fails the script on any non-2xx, printing the body APISIX sent back -
# silently ignoring a rejected route is how you end up with a gateway that
# 404s in production for no visible reason.
call() {
  local method="$1" path="$2" body="${3:-}"
  local response status

  if [ -n "$body" ]; then
    response=$(curl -sS -w $'\n%{http_code}' -X "$method" "${ADMIN_URL}${path}" \
      -H "X-API-KEY: ${ADMIN_KEY}" \
      -H "Content-Type: application/json" \
      -d "$body")
  else
    response=$(curl -sS -w $'\n%{http_code}' -X "$method" "${ADMIN_URL}${path}" \
      -H "X-API-KEY: ${ADMIN_KEY}")
  fi

  status="${response##*$'\n'}"
  body="${response%$'\n'*}"

  case "$status" in
    2*) echo "  ${method} ${path} -> ${status}" ;;
    404)
      if [ "$method" = "DELETE" ]; then
        echo "  ${method} ${path} -> 404 (already gone)"
      else
        echo "  ${method} ${path} -> ${status}: ${body}" >&2
        return 1
      fi
      ;;
    *)
      echo "  ${method} ${path} -> ${status}: ${body}" >&2
      return 1
      ;;
  esac
}

if [ "${1:-}" = "--delete" ]; then
  echo "Removing billing gateway routes from APISIX at ${ADMIN_URL}"
  # Routes first: an upstream still referenced by a route cannot be deleted.
  call DELETE "/apisix/admin/routes/${ROUTE_ADMIN_ID}"
  call DELETE "/apisix/admin/routes/${ROUTE_MOBILE_ID}"
  call DELETE "/apisix/admin/upstreams/${UPSTREAM_ID}"
  echo "Done."
  exit 0
fi

echo "Seeding billing gateway routes into APISIX at ${ADMIN_URL}"
echo "  upstream node: ${UPSTREAM_NODE}"

# ---------------------------------------------------------------------------
# Upstream: the internal gateway's REST/JSON listener.
#
# Resolved by name through cluster DNS on every request, so a pod restart
# behind the ClusterIP needs no re-seed. Read timeout is generous because a
# single call here can fan out to the billing/subscription service and then
# on to Medusa.
# ---------------------------------------------------------------------------
call PUT "/apisix/admin/upstreams/${UPSTREAM_ID}" "$(cat <<EOF
{
  "desc": "autofik.dev.api.billing.getway.internal - grpc-gateway REST listener",
  "type": "roundrobin",
  "scheme": "http",
  "pass_host": "pass",
  "timeout": { "connect": 5, "send": 30, "read": 30 },
  "nodes": { "${UPSTREAM_NODE}": 1 }
}
EOF
)"

# ---------------------------------------------------------------------------
# Public mobile surface.
#
# Paths are forwarded unchanged: the gateway's grpc-gateway mux already
# serves /mobile/v1/... exactly as declared in billing.proto, so there is no
# proxy-rewrite and no grpc-transcode plugin - the gateway transcodes
# REST <-> gRPC itself.
#
# APISIX does not authenticate here. Every route except /mobile/v1/health
# is authenticated inside the gateway by UserVerificationUnaryInterceptor,
# which verifies the bearer token against user.auth.sso, so the Authorization
# header only has to survive the hop - which it does, untouched.
#
# Note /internal/v1/token/verify is deliberately NOT routed. It is for
# in-cluster callers only; they reach it on the ClusterIP Service
# (billing-getway-internal:8081 / :50055), never through the edge.
# ---------------------------------------------------------------------------
call PUT "/apisix/admin/routes/${ROUTE_MOBILE_ID}" "$(cat <<EOF
{
  "name": "billing-getway-mobile",
  "desc": "Mobile REST surface of the internal billing gateway",
  "uri": "/mobile/v1/*",
  "methods": ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS", "HEAD"],
  "priority": 0,
  "upstream_id": "${UPSTREAM_ID}",
  "plugins": {
    "cors": {
      "allow_origins": "*",
      "allow_methods": "GET,POST,PUT,PATCH,DELETE,OPTIONS,HEAD",
      "allow_headers": "Authorization,Content-Type,Accept,x-publishable-api-key",
      "max_age": 3600,
      "allow_credential": false
    }
  }
}
EOF
)"

# ---------------------------------------------------------------------------
# Admin surface - same upstream, separate route so it can be locked down
# independently.
#
# Higher priority than the /mobile/v1/* route above, which also matches these
# paths; APISIX picks the higher priority when several routes match.
#
# The uris list is not just the /admin/ prefix: ApproveBilling and
# RejectBilling are admin operations that live under /mobile/v1/billings/ in
# billing.proto, so restricting only /mobile/v1/admin/* would leave them
# wide open.
#
# IMPORTANT: the gateway itself does not check roles on these RPCs - it
# proxies them with the caller's own token and lets the billing/subscription
# service decide. Set ADMIN_ALLOW_CIDRS to keep the admin surface off the
# public internet unless you have confirmed those services reject a
# non-admin role.
# ---------------------------------------------------------------------------
admin_plugins='{
    "cors": {
      "allow_origins": "*",
      "allow_methods": "GET,POST,OPTIONS",
      "allow_headers": "Authorization,Content-Type,Accept,x-publishable-api-key",
      "max_age": 3600,
      "allow_credential": false
    }'

if [ -n "$ADMIN_ALLOW_CIDRS" ]; then
  # a.b.c.d/32,e.f.g.h/24 -> "a.b.c.d/32","e.f.g.h/24"
  whitelist=$(printf '%s' "$ADMIN_ALLOW_CIDRS" | tr ',' '\n' | sed 's/^[[:space:]]*//;s/[[:space:]]*$//' |
    grep -v '^$' | sed 's/.*/"&"/' | paste -sd, -)
  admin_plugins="${admin_plugins},
    \"ip-restriction\": { \"whitelist\": [${whitelist}] }"
  echo "  admin routes restricted to: ${ADMIN_ALLOW_CIDRS}"
else
  echo "  WARNING: ADMIN_ALLOW_CIDRS is unset - the admin endpoints are"
  echo "           reachable by any authenticated caller from the internet."
fi

admin_plugins="${admin_plugins}
  }"

call PUT "/apisix/admin/routes/${ROUTE_ADMIN_ID}" "$(cat <<EOF
{
  "name": "billing-getway-admin",
  "desc": "Admin surface of the internal billing gateway",
  "uris": [
    "/mobile/v1/admin/*",
    "/mobile/v1/billings/approve",
    "/mobile/v1/billings/reject"
  ],
  "methods": ["GET", "POST", "OPTIONS"],
  "priority": 10,
  "upstream_id": "${UPSTREAM_ID}",
  "plugins": ${admin_plugins}
}
EOF
)"

echo "Done. Smoke test (no token needed on the health route):"
echo "  curl https://apisix.master.autofik.com/mobile/v1/health"
